# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dea4d77bc214ded01b034b1eaa894b18b79147f616e6a3da3fe70eb037537836a23a54526fd7e5fc7650c606beb07ac941b88859f24f4270d99b9d24a552e696

test:
  secret_key_base: 42226e3d3e234206ea5a376f598de52ceb141d07fef01b5563c9c78d131ee397dd5d2ee6592de833d5e54b15576ce45c8c704b4de92b45320c44cdd9e4115e02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
